sanack/node-jq

- package.json
- src/jq.js
- test/jq.test.js
I came up with some idea for create the options map:
```js
const optionsMap = [
{
nullInput: {
flag: '--null-input',
buildParams: (filter, json) => {
return [
'--null-input',
`${filter} | ${JSON.stringify(json)}`
]
}
}
// [...]
}
]
```
I didn't implemet it yet, because I only have 1 option and I want to know if this make sense in the jq parameters. 
This PR it's just the first approach that I made, after the duplicity that in master exist.
Solves this: https://github.com/davesnx/node-jq/issues/1
> Refactor command builder

- package.json
- src/jq.js
- src/utils.js
- test/jq.test.js
- test/utils.test.js
Depends on https://github.com/davesnx/node-jq/pull/5
Here I'm only splitting up the utils from the `jq.js` entry point and doing the same with the tests.
Also, I remove the assertions of chai (😢 ) and replace it with the `chai-as-promised` interface, using `eventually` that works fine with the async operations. [Source](https://github.com/domenic/chai-as-promised)
Also adding a *FIXME* comment on top of `isAJson()` that does a try catch trying to parse the json, it's pretty slow we can replace it checking the keys of the object or whatever.
> Refactor utils and tests

- src/utils.js
- test/jq.test.js
- test/options.test.js
- test/utils.test.js
Making tests more consistent and clear
> Refactor tests

- README.md
- src/jq.js
- src/options.js
- test/jq.test.js
- test/options.test.js
Proposal for option mapping.
I believe that this way it's easier to distinguish between `file`, `json` and `string` input (defaulting to file input). Output is either `json` or `string`. 
(I thought `nullInput` wasn't descriptive enough)
Todo in this PR:
Optional: Add more options as you see fit ([jq-manual](https://stedolan.github.io/jq/manual/))
> Add option mapping with defaults

- package.json
- src/command.js
- src/exec.js
- src/jq.js
- src/options.js
- src/utils.js
- test/fixtures/1.js
- test/jq.test.js
- test/options.test.js
- test/utils.test.js
Hello @mackermans 
This is the first refactor for prepare the next releases, one exporting jq.run as jq directly and the other for support json5.
The intention is to separate how we create the command and how we run it.
- Create a commandFactory.
- Remove `isAJson` util not used and his tests.
- Rename json to capital letters.
- Rename `chai-as-promised` to `promised` on the tests.
> Improve internal API

- src/jq.js
- test/fixtures/1.json
- test/jq.test.js
- test/options.test.js
Hello @mackermans and @wellsjo
- Add a test case for ur use case.
- Try to parse the output as a JSON, if we can't we pass it directly. That will affect, numbers, strings and arrays. It's the minimum effort to not break the API of the output.
As you can see in the test, the output of
```bash
jq_ "{ prop: [1,2,3] } | .prop[]" --null-input
1
2
3
```
That means that you can't actually parse this string of `"1\n2\n3\n"` with JavaScript. Thinking a solution like sending back the type of the source of the result could be a nice one, but we need to be sure that matches without properties of output. 
I keep this 3 series of PR lately keeping in mind that the repetition is better than the wrong abstraction and a small patch here with good test coverage can be improved drastically at the end of the …
> Don't parse the result on output:json if isn't a valid JS format

- package.json
- scripts/install-binary.js
- test/fixtures/1.json
- test/jq.test.js
- test/options.test.js
Jq can't be build by a command in windows, there is no config file for windows yet.
My solution to this is to download the executable and not the source.
So I use a map to find which file is the executable for the platform and arch:
```js
const DOWNLOAD_MAP = {
'win32': {
'def': 'jq-win32.exe',
'x64': 'jq-win64.exe'
}
}
```
If the platform is not in the map the old ways apply (download, config, make).
If you want you can add more this like:
```js
const DOWNLOAD_MAP = {
'win32': {
'def': 'jq-win32.exe',
'x64': 'jq-win64.exe'
},
'linux': {
'def': 'jq-linux32',
'x64': 'jq-linux64'
}
}
```
- A `win32` platform can be 64-bit
- Made the executable filename variable because in windows is `jq.exe` and not `jq`
- The dep `download` that I added is already used by the `bin-build`
The absolute paths …
> Windows compatibility

- .travis.yml
- package.json
- yarn.lock
BREAKING CHANGE: Dropped support for NodeJS v4. node-jq now requires NodeJS v6+
NodeJS v4 has moved from Active LTS to Maintenance LTS in April 2017, and will be unsupported as of April 2018 ([source](https://github.com/nodejs/Release)).
> Require node engine  >=6.0.0

- package.json
- scripts/install-binary.js
- yarn.lock
The command `npm audit` reports several vulnerabilities in the node-jq project. This PR attempts to resolve those vulnerabilities.
Here is the current output of `npm audit`:
```
$ npm audit
=== npm audit security report ===                        
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ isparta [dev]                                                │
├───────────────┼───────────────────────────────────────────────── …
```
> [WIP] fix: get npm audit to pass

- README.md
- src/command.js
Makes it possible to control where the jq binary that should by used is located.
I'm using this on AWS Lambda where I add the jq binary using a lambda layer. Unfortunately one is limited in controlling where AWS puts the binary. So this is useful for anyone who does not want or is not able to use the default binary location.
I also updated the docs :)
> feat(jq): added ability to optionally specify jq binary location

- src/command.js
- src/utils.js
- test/jq.test.js
- test/options.test.js
Replicates behavior prior to addition of stdin feature (PR #194) and fixes #195 
A future release could drop some of these errors and actually handle invalid input gracefully - that would require a breaking/major release.
(Apologies for the big diff, linter at work)
> fix(stdin): throw errors on invalid input

- package.json
- yarn.lock
Gets rid of outdated and insecure `diff` dependency (version < 3.5.0).
> Remove unused tap-diff package

- .vscode/launch.json
- package.json
- src/command.d.ts
- src/command.js
- src/exec.d.ts
- src/exec.js
- src/jq.d.ts
- src/jq.js
- src/options.d.ts
- src/options.js
- src/utils.d.ts
- src/utils.js
- test/command.test.js
- test/jq.test.js
- test/options.test.js
- yarn.lock
As requested a more modest update that adheres to existing exports. 
- swaps out builder system for Joi
- unifies filter, json, and option validation
- adds a JQ class that accepts a custom jqPath and SpawnOptions
- existing functions updated to accept custom jqPath and SpawnOptions
- typescript definition files for each js created
- support for locations and color options
- 100% code coverage
> Use Joi for validation & typescript definitions

- src/exec.js
I added `process.stdio.setEncoding('utf-8')` to exec.js.
This is because without this code, the output containing multibyte characters will be garbled.
> fix: Add process.stdout.setEncoding

- scripts/install-binary.js
Add Linux binaries to the download map so we don't need to compile from scratch.
> Add binaries for linux into download map

- scripts/install-binary.js
We need the read permission so that the build system can pack the `node_modules/` folder.
i.e. build with Heroku CI/CD, docker build, etc.
> Add `read` permission to the downloaded `jq` binary

- scripts/install-binary.js
Continue:
- #437 
After testing the published version, I found that the permission number is not right.
I suggest that we can just use `0755` which is `-rwxr-xr-x`
```sh
$ chmod 0755 bin/jq
$ ls -l bin/
total 3864
-rwxr-xr-x 1 huan huan 3953824 Nov 15 23:59 jq
```
```ts
// fs.constants.S_IXUSR 64
// fs.constants.S_IROTH 4
// fs.constants.S_IRGRP 32
// fs.constants.S_IREAD undefined
console.info(fs.constants.S_IXUSR | fs.constants.S_IREAD | fs.constants.S_IROTH | fs.constants.S_IRGRP)
// 100 (0144)
console.info(0o100 | 0o400 | 0o040 | 0o004)
// 0544
```
> use `chmod 0755`

- src/exec.js
- src/jq.test.js
We discovered a bug where large payloads can cause unhandled errors. This is a fix for that bug.
In the `exec` method defined in `src/exec.js`, the child process is spawned, then the JSON data is sent to stdin, and then listeners are added. The problem here is that the child process can exit while we are still writing to its stdin. If this happens, its stdin will also close, and will generate a low-level `EPIPE` error event, as we will be writing to a closed pipe. Nothing will handle that error event.
```javascript
const process = childProcess.spawn(command, args, spawnOptions)
if (stdin) {
process.stdin.setEncoding('utf-8')
process.stdin.write(stdin) // <- This line can take a while to complete, during which the child process can exit.
process.stdin.end()
}
// ... other listeners …
```
> fix: Set up listeners first, in case of long write to stdin.

- package-lock.json
- package.json
- scripts/install-binary.js
This PR replaces the `download` package that has some vulnerabilities for the package `node-downloader-helper`.
A vulnerability with a high risk that `download` has:
https://github.com/advisories/GHSA-pfrx-2q88-qq97
I chose `node-downloader-helper` because is being maintained actively and the API is as simple as `download`'s.
I ran `npm run test` and all the tests passed.
Closes #515
> fix: Change download package for node-downloader-helper

- src/exec.js
- src/options.test.js
This pr stops implicitly sending the current execution env into the JQ execution (which can be read with "$ENV" in the jq filter).
I added a test that demonstrates the issue, if you back the change to src/exec.js out, you'll see that the entire collection of environment variables will get reflected in the output object.
> stop sending process.env into jq execution

- .github/workflows/ci.yml
- package-lock.json
- package.json
@davesnx We're officially dropping support for Node v10 — though I think we already weren't testing different Node.js versions in the CI test matrix.
An incorrect reference `runner.node-version` was used in the GH Actions workflow, which was undefined. I fixed the reference by renaming it to `matrix.node-version` in https://github.com/sanack/node-jq/pull/606/commits/8d867733e5d632d44dc94849afb357a1984d2746. After that the Node v10 build started failing. See https://github.com/sanack/node-jq/actions/runs/5732042212/job/15534213902
I also disabled the CodeClimate code coverage reporter, since that failed on Windows. Supposedly that was fixed in [v5.0.0](https://github.com/paambaati/codeclimate-action/releases/tag/v5.0.0), but still the build failed. Will come up with a follow-up PR to …
> Remove support for Node v10, test Node v18 and v20

- README.md
- scripts/install-binary.js
- src/jq.test.js
To follow the new [jq 1.7](https://github.com/jqlang/jq/releases/tag/jq-1.7) release, I made some changes.
- Update links in README.md to the new jqlang organization.
- Update download map to follow changes of executable names.
- Simplify building commands from source code.
- Remove test of empty filter unsupported in 1.7.
> Bump up to jq 1.7

- README.md
- src/exec.d.ts
- src/exec.js
- src/jq.d.ts
- src/jq.js
- src/jq.test.js
when an app receives SIGTERM it propagates it to a child `jq` process and `node-jq` throws an error.
this makes graceful shutdown of an app impossible. 
this PR allows `jq` to run as detached process so that SIGTERM is not propagated allowing it to exit normally.
> option to run jq as detached process

- .github/issue_template.md
- package-lock.json
- package.json
Allows `npx node-jq "." package.json` (and `npx jq "." package.json` if you already installed node-jq)
Side note: Includes a chance to the issue_template I had on `main` (mb)
> Add jq bin field to package.json

- README.md
- src/options.d.ts
- src/options.js
- src/options.test.js
node-jq is an excellent library. However it is a bit limited by functionality. I added the capability to send custom args to the jq command to fully unlock the functionality and make it available via this library.
> Add custom args to options

- package.json
It appears that if bin/jq doesn't exist during the npm install target,
it won't get symlinked to ~/node_modules/.bin
So fetch it in preinstall instead
fixes: #669
> fix: ensure bin/jq symlinked to node_modules/.bin

- src/exec.js
This PR fixes https://github.com/sanack/node-jq/issues/681
* remove setEncoding on a Writable stream (break [bun](https://bun.sh) runtime)
The reason behind this issue is that `Writable.setEncoding` is not part of the node API and will break in the [bun](https://bun.sh) runtime. Since "utf8" is the default encoding anyways, this setting should be safe to be removed.
> fix: remove setEncoding on write stream

- scripts/install-binary.js
1.7.1 has been released in Dec 2023, including two buffer overflow fixes:
https://github.com/jqlang/jq/releases/tag/jq-1.7.1
> Update jq version to 1.7.1

- README.md
- scripts/install-binary.mjs
- src/command.ts
This PR introduces a new configuration mechanism that allows users to specify a local `jq` binary path through their `.npmrc` file, enabling the use of `node-jq` in restrictive environments where downloading binaries is prohibited.
Currently, `node-jq` downloads the `jq` binary during installation from GitHub releases. This approach fails in environments with:
- **Network restrictions**: Corporate firewalls that block downloads from external sources
- **Security policies**: Organizations that prohibit downloading executables during build processes
- **Immutable environments**: Container builds or CI/CD pipelines where external downloads are not allowed
- **Configuration constraints**: Environments where setting arbitrary environment variables during install, build, or runtime is not …
> feat: add support for local jq binary via .npmrc configuration

- .eslintignore
- .git-blame-ignore-revs
- README.md
- lefthook.yml
- package-lock.json
- package.json
- scripts/install-binary.mjs
- src/command.ts
- src/jq.test.ts
- src/jq.ts
- tsconfig.eslint.json
- tsconfig.json
- BREAKING: If JQ_PATH is set, don't run the install binary script. Align behaviour from JQ_PATH with npm_config_jq_path https://github.com/sanack/node-jq/pull/724
- BREAKING: Remove jqPath from run
- BREAKING: Absorbs https://github.com/sanack/node-jq/pull/691 and fixes #689
- Run eslint in scripts
- Update lefthook to latest
> Ensure jq path doesnt download
