sanack/node-jq

- README.md
I create a gitter channel for receive feedback about the lib. 
https://gitter.im/davesnx/node-jq
> Adding npm and gitter label on README.md

- src/jq.js
> Fix null input option

- src/jq.js
- src/options.js
- test/jq.test.js
- test/options.test.js
- test/utils.test.js
> Refactored options

- .travis.yml
- README.md
- package.json
> Added Travis build config file

- .travis.yml
- README.md
> Small change to release status badge

- README.md
> Now really fixed the Travis build badge

- package.json
* New github url
* Added myself as collaborator
* Added emails
> Updated package information

- .gitignore
- README.md
- circle.yml
- package.json
- scripts/install-binary.js
- scripts/install-jq.js
- Fixes README stuff
- Add the `install-jq-binary` with the following steps:
- Check if jq is installed globally?
- Check if jq is installed locally with the version defined (TODO)
- Check os
- Download according to the OS
- Install it into the `node-jq/node_modules/.bin` folder
- Added a test for that
> Feature binary

- package.json
- scripts/install-binary.js
This PR solves https://github.com/sanack/node-jq/issues/45 and reduces the complexity of `install-binary`
> Fix install binary

- README.md
- circle.yml
- package.json
@davesnx 
This will improve our way of versioning and enforces a standard for commit messages.
> Automatic semantic releases

- .gitignore
- README.md
- package.json
- scripts/install-binary.js
- src/jq.js
@davesnx @wellsjo 
This PR should solve https://github.com/sanack/node-jq/issues/47
> Always use locally installed jq binary

- package.json
> build(husky): replace ghooks with husky

- README.md
- package.json
- Add examples of all the options
- Explain the context of why
- Adding use-cases
- Add appvoyer label
- Add learning jq section
PS: The only part that I miss here is the Contribution section, but for now I woudn't add it now.
Taking a look into the changes is useless, check https://github.com/sanack/node-jq/tree/Improve_Documentation
Solves https://github.com/sanack/node-jq/issues/34
> Improve documentation

- package.json
> chore(package): update download to version 5.0.3

- package.json
> chore(package): update validate-commit-msg to version 2.10.1

- package.json
- test/utils.test.js
> Update StandardJS to version 9.0.0

- package.json
> chore(package): update validate-commit-msg to version 2.11.2

- yarn.lock
> build(yarn): upgrade dependencies in yarn.lock

- src/command.js
- src/exec.js
- src/jq.js
- src/options.js
- test/fixtures/var.json
- test/jq.test.js
> Prevent shell variable expansion

- README.md
- src/options.js
- test/options.test.js
`jsonPath` parameter can now also be an array of paths.
> Allow multiple files input

- src/options.js
I needed to be able to access the color option for my output.
> added color option

- package.json
- yarn.lock
> Move travis-deploy-once to devDependencies

- package.json
> Create bin entry

- scripts/install-binary.js
* Download darwin executable binary instead of compile source code
* Add executable permissions to downloaded binary file
* Exit with status code 1 if download/compile failed
> Enhance scripts/install-binary.js

- package.json
> feat(package): add jq to path on install

- src/options.js
- test/options.test.js
Support '-r' options for jq by setting  options.raw = true
> Add '-r' (output raw string) support for jq

- README.md
> Update readme to match expected behaviour #171

- .vscode/launch.json
- package.json
- src/command.d.ts
- src/command.js
- src/exec.d.ts
- src/exec.js
- src/jq.d.ts
- src/jq.js
- src/options.d.ts
- src/options.js
- src/utils.d.ts
- src/utils.js
- test/command.test.js
- test/jq.test.js
- test/options.test.js
- yarn.lock
Releases #203 with the Joi package updated to the latest version.
> Typescript and Joi schema validation

- README.md
As mentioned https://github.com/sanack/node-jq/issues/163, This PR clarifies the documentation regarding post-install script and some other wording
cc @kseniamukhortova
> Improve documentation regarding advanced installation

- package-lock.json
- package.json
- release.config.js
- Publish to NPM
- Don't update package.json with semantic-release git plugin
> ci: fix release
